### ISSUE TITLE
Thumbnails are not being imported via MRSS

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/sms2jwplayer#14]
jwplayer help desk believes this is because our thumbnail urls do not have extension:

"I have not yet heard back from the product manager regarding your image URLs. As a troubleshooting step, are you able to append a file extension onto the end of those image URLs? Our product manager wants to test that, if possible."

Currently they look like: <media:thumbnail url="https://sms.cam.ac.uk/image/2625098" />
Try <media:thumbnail url="https://sms.cam.ac.uk/image/2625098.jpeg" />

**Comment by rjw57** [comment]
We don't care about this any more since we're moving to using only API to update JWPlayer.
