### ISSUE TITLE
Import thumbnails via API

### ISSUE THREAD

**Issue by rjw57** [uisautomation/sms2jwplayer#17]
We should import thumbnails via the JWPlayer API. It's a little non-trivial since this would also require having some way of determining when we have set the thumbnail for a video. This could be via a custom "has_custom_thumbnail" prop or similar.

1) Store in the custom tags in jwplayer: SHA256 of the uploaded thumbnail
2) check if the last_updated is different and do a diff of the SHA256 of the thumbnails
3) upload the new one if that is the case

**Comment by abrahammartin** [comment]
Done now
