### ISSUE TITLE
A small number of legacy thumbnails have been rejected by the JWPlatform

### ISSUE THREAD

**Issue by msb** [uisautomation/sms2jwplayer#20]
The Media with failed thumbnails have the following ID's

["CH1I7pV5", "lnofXM2B", "DmiUcPDi", "vP23xKnA", "Bx8Lpj5g", "4I0VFaSX", "3EKYfUYs", "cpheb61r", "jIq3eQaj", "9ompbQzv", "OyhjGBk0", "ddoTusWl", "T4zSsDXC", "lOvCUqc0", "Y73XQXil", "e2P2yKpd", "2n23HSfU", "uXVBwsBh", "ytDNtxXp", "3GuMOeRf", "FZTYuqsl", "H9ESKaid", "673UpHu7", "x4Z2cdab", "vz5a2RqD", "YneFGNYh", "bWz8bqdB", "4NhzOC3L", "6g4dFt2z", "OB2VDfz5", "o2SgWyot", "0ibtPM8K", "ILAuDbw5", "FGZ9zVFP", "QC1ryw7O", "hvwzYwZm", "zLiuDUZR", "iF3tOAUD", "0yod9muF", "MQc6oayY", "5QF6hLHp", "ZYYHooK5", "NqoVASRT", "lAxmJ88d", "wLErafhA", "Y3u1VSck", "MJdosFK9", "5mLqFhxx", "0Ynyeold", "tMfllWOr", "xp0E6XS7", "nU2y2HmM", "KE1eVByV", "lV8wZ2mx", "1ZTA9gQT", "v1292Pfo", "YJ6FC5jM", "v7Rdhbew", "DXB5oNUx", "z1Vc4Zbt", "qvCZc6Q5", "nxbvXyz6", "NJQJSPYs", "n5JSR4gf", "ulKILH54", "tZhTcMIR", "W1Zt39KE", "MF0eRLGg", "vI7T9BGU", "ndlq61RD", "ukYorvu4", "MngtePaz", "YcW7Mi1Q", "zTOUO6h0", "7K8Qr77h", "QwC5CXnm", "MVY7wlC6", "BIwFiNPK", "y1fkPbkh", "snr59c6g", "q5FNMFDY", "mC0by7CM", "MdcLX5wQ", "uMRJbYXn", "j00BivV1", "PXiTJYPu", "8A3YDmeb", "KUBPRPRM", "8W5rDMA6", "nxnnhz7d", "VEFZAP30", "SUlKhcWd", "F0kuOuyD", "U31PJBNT", "nuguYyEX", "CPS6T2Ej", "BOA26UIZ", "m73bsEc6", "sM0oDcmI", "ZABYHToh", "XGsaMKGy", "juDXN0h7", "YvoJCowW", "9PGT7BCg", "1gi6p9Kb", "xYG20p4Y", "yD11pkxv", "s76i451M", "05uzKJI9", "tXdRtD4L", "iNAW8vXR", "MV382WwP", "qLdp8vKw", "Neq2oTzJ", "5nrBqCkb", "FIXEIn3H", "RvPql28y", "uDz1EjH1", "gsaIuMG9", "h5Rvg6ly", "h4oPKzEA", "csn4Qp6j", "1Mw6vefE", "k8GwG3Yz", "Btp6FzI0", "3iQA621a", "dl1SDfWz", "kW4uGDYM", "OhLkb9gj", "kzUdnkC6", "EPttOaIs"]

79 of these 131 are GIFs - so I guess it's fairly safe to assume that converting these to JPG's would leave only 52 fails to investigate.

**Comment by msb** [comment]
I produced the spreadsheet below by retrieving the unique thumbnail images for all the imported videos and running the bash file command on them. The points to note are:

1. There are 50 'unique' thumbnails that have failed.
2. All GIFs (27) have failed.
3. Small thumbnails do NOT seem to be a factor, ie, a lot of small images have failed but there are plenty that were successful too.

[thumbnail-data.xlsx](https://github.com/uisautomation/sms2jwplayer/files/2047738/thumbnail-data.xlsx) ([Google sheet](https://docs.google.com/spreadsheets/d/1AsVjZRZbLXJMjfQRp-ORfYx6Sot8Hz3-W0vs90Lkaks/edit))

Conclusion: there aren't enough fails to justify taking any immediate action.

**Comment by rjw57** [comment]
> thumbnail-data.xlsx

I have uploaded this as a [Google Sheet](https://docs.google.com/spreadsheets/d/1AsVjZRZbLXJMjfQRp-ORfYx6Sot8Hz3-W0vs90Lkaks/edit) to the Team Drive.

**Comment by rjw57** [comment]
> Conclusion: there aren't enough fails to justify taking any immediate action.

:+1:
