### ISSUE TITLE
Move away from :[type]:[value]: custom props

### ISSUE THREAD

**Issue by rjw57** [uisautomation/sms2jwplayer#33]
Now we're using our own database, we need not have the hacky ``:[type]:[value]:`` format for custom props. To avoid breaking our existing app, I suggest adding a new set of custom props prefixed by ``legacy_``. E.g.:
```js
{
  // ...
  custom: {
    // ... existing sms_... props
    legacy_media_id: "12345",
    legacy_... // etc
  }
}
```
Then, once we've migrated sms-webapp to understand them, we can just remove the logic which updates ``sms_...`` props and add deleting them to the tidyup job.

**Comment by abrahammartin** [comment]
We are going to move to use our own DB, so no longer needed.
