### ISSUE TITLE
Migrate all ACLs from old SMS -> new

### ISSUE THREAD

**Issue by msb** [uisautomation/sms2jwplayer#7]
Depends from #5 

Move all old SMS to the new model done in #5. The old SMS uses ACLs with mixed crsid, group_id, and inst_id. We need to move all of this to the new model. We also want to the new model the current visibility list: 

        # -- Visibility - who is allowed to see the video.
        # -- world - media item is world visible unless restricted by acl
        # -- cam   - media item is cam visible unless restricted by acl
        # -- world-overrule - media item is world visible regardless of acl
        # -- cam-overrule   - media item is cam   visible regardless of acl
        # -- acl-overrule   - media item is restricted by its acl field regardless of acl****

moved from: https://github.com/uisautomation/sms-webapp/issues/42

**Comment by rjw57** [comment]
Closed via #8
